# Generated by Django 3.1.7 on 2021-03-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='co2_sensor',
            new_name='sensor_data',
        ),
    ]
