# Generated by Django 3.1.7 on 2021-04-09 14:34

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20210326_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='sensor_gps_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
