# Generated by Django 3.1.7 on 2021-04-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_auto_20210409_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='temperature',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
