# Generated by Django 3.1.7 on 2021-04-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_sensordata_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='daily_upload_frequency',
            field=models.IntegerField(default=8640),
            preserve_default=False,
        ),
    ]
