# Generated by Django 3.1.7 on 2021-04-17 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_sensor_daily_upload_frequency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='daily_upload_frequency',
            new_name='frequency',
        ),
    ]
