# Generated by Django 3.2 on 2021-04-22 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_auto_20210417_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='imei',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='sensors.sensor'),
        ),
    ]
