# Generated by Django 3.2 on 2021-04-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_auto_20210422_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='imei',
            new_name='imei_sensor',
        ),
    ]
