# Generated by Django 3.2 on 2021-04-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0010_auto_20210422_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='imei',
            field=models.BigIntegerField(unique=True),
        ),
    ]
