# Generated by Django 3.2 on 2021-04-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0011_alter_sensor_imei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='imei',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
